In [1]:
from numpy import *

In [2]:
def gerar_matriz(n_linhas)->list:
    return((identity(n_linhas, dtype=float)))

In [3]:
print(gerar_matriz(int(input("Número de linhas: "))))

Número de linhas: 9
[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [4]:
def igual(n:list)->bool:
    for i in range(len(n)):
        repete=n.count(n[i])-1
    if repete >=1:
        return True
    else:
        return False

In [5]:
l = [1,3,2,4,5,3,2,4,6,3,2]

In [6]:
igual(l)

True

In [7]:
def contida(l1:list,l2:list)->bool:
    if all(l2 == l1):
      return True
    else:
      return False

In [8]:
l1 = [1,2,3]
l2 = [1,2,3]

In [9]:
type(l)

list

In [10]:
contida(l1,l2)

True

In [11]:
from typing import Tuple, TypeVar
T1 = TypeVar('T1')

def reverter(t:Tuple[T1])->T1: 
    nova = tuples[::-1] 
    return nova

In [12]:
tuples = (10, 11)

In [13]:
type(tuples)

tuple

In [14]:
reverter(tuples)

(11, 10)

In [15]:
type(reverter(tuples))

tuple